### PR TITLE
Create buggy_html.html

### PR DESCRIPTION
**Pull request by KDunc-MSFT**
Created intentionally flawed HTML code to try and trigger a scan.

### CODE REVIEW

**Comment by weistrofferkl** [comment]
Checking out this PR!

**Review by weistrofferkl — CHANGES_REQUESTED** [review]
Pls Fix Line 8.

**Review by dreammsin — DISMISSED** [review]

**Comment by KDunc-MSFT** [comment]
> Pls Fix Line 8.

Fixed.

**Review by weistrofferkl — APPROVED** [review]
Looks Gucci

**Pull request merged**
